### ISSUE TITLE
Second private key?

### ISSUE THREAD

**Issue by omki2005** [fyookball/keys-n-hashes#15]
I'm not sure why the second public key is there? Perhaps you meant to sign the second key with the first one?

I don't know if I should trust any signatures from the second key or not... Maybe an announcement on electron cash website might help?

**Comment by fyookball** [comment]
I had posted a response on reddit to the same question.

I made a mistake due to inexperience with GPG and didn't back up the key.  It was accidentally deleted and I believed I would be able to restore the key with the public key and my GPG passphrase.  Turns out the passphrase does not generate the private key, but only decrypts it.  Sorry about that.

**Comment by fyookball** [comment]
BTW, deterministic builds are coming to remove need for trust.  Currently 3.0 is done in that way and we are working through any bugs so people get the same exe checksum.
