### ISSUE TITLE
key signature problem

### ISSUE THREAD

**Issue by 33bit** [fyookball/keys-n-hashes#19]
$ gpg --import ElectronCashPubKeyDev/jonaldkey2.txt

gpg: key EFF1DDE1: "Jonald Fyookball <jonf@electroncash.org>" not changed
gpg: Total number processed: 1
gpg:                          imported: 1

Was ok...

$ gpg --verify ElectronCash-3.1.2.tar.gz.sig ElectronCash-3.1.2.tar.gz

gpg: Signature made 2018. jan.  9., tuesday, 07:34:56 CET using DSA key ID EFF1DDE1
gpg: Good signature from "Jonald Fyookball <jonf@electroncash.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D56C 110F 4555 F371 AEEF  CB25 4FD0 6489 EFF1 DDE1

Fail...

**Comment by fyookball** [comment]
A "trusted signature" is a signature from a key that you trust, either because (a) you have personally verified that it belongs to the person to whom it claims to belong, or (b) because it has been signed by a key that you trust, possibly through a series of intermediate key

source: https://serverfault.com/questions/569911/how-to-verify-an-imported-gpg-key
